### ISSUE TITLE
Add maintainer

### ISSUE THREAD

**Issue by emaxerrno** [smfrpc/smf-go#2]
@crackcomm  - hey man, with the addition of python from @noahdesu I'd love to give you maintainer access to the smf-go repo so you can maintain this subrepo and we start to build a bigger community. 

Thoughts?

**Comment by crackcomm** [comment]
@senior7515 I can certainly help with Go, with addition of Python implementation it would be really useful to create integration tests so we can test implementations against each other, it could be done by building docker images for each and then using `--link` to C++/Go/Python implementations. It would give something to test against. Benchmarking would be a dream - easy for Python https://pv.github.io/numpy-bench/

I would like to keep Go implementations as simple as possible. Currently server implementation works by accepting each client in a goroutine and does processing in same goroutine. I think it's hard to choose because in different cases most efficient methods are not the same.

Channels are not the most effective way but we don't want to spawn a goroutine for each call with use of locks.

This is why I believe there has to be a choice so the calling isn't actually more expensive than underlying method (for example simple map lookup). It should be suitable per-method not necessarily per-service.

I hope you understand the advantage it can give in many cases when most of the responses come straight from memory.

**Comment by emaxerrno** [comment]
@crackcomm  great on the maintainer, will give you write access. I think the current impl is good enough for now. We can improve later as needed. 

w.r.t cross language benchmarking - agree. 

I think what we need for go tho, is a fully worked out example, maybe forking and adding Go here: 

https://github.com/smfrpc/smf-getting-started-cpp

(we can rename the repo to simply `smf-getting-started`)

It already has all the cmake-foo needed to build / download the cpp / compiler / etc.

**Comment by emaxerrno** [comment]
@crackcomm  - to make sure you got it, please close this issue when you get write access.

**Comment by dotnwat** [comment]
> create integration tests so we can test implementations against each other

great idea. i think expanding the cpp example as a reference impl for testing these language implementations is the way to go. the service definition needs to be expanded, though, to be a little more realistic, i think. at least so it's returning data and using filters.
